# Remove trailing slash
{{ $bdir := regexSplit ( list .chezmoi.homeDir "/" | join "" ) .bindir -1 | last }}
{{ $cdir := regexSplit ( list .chezmoi.homeDir "/" | join "" ) .compdir -1 | last }}


[".zim/zimfw.zsh"]
type = "file"
url = "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
refreshPeriod = "168h"                                                    # 1 week

{{ $exaVersion := (gitHubLatestRelease "ogham/exa").TagName  -}}
["{{- $bdir -}}"]
    type = "archive"
    url = "https://github.com/ogham/exa/releases/download/{{ $exaVersion }}/exa-{{ .chezmoi.os }}-x86_64-{{ $exaVersion }}.zip"
    executable = true
    extract = true
    stripComponents = 1
    include = ["bin/exa"]
    refreshPeriod = "168h"

["{{- $cdir -}}/_exa"]
    type = "file"
    url = "https://raw.githubusercontent.com/ogham/exa/master/completions/zsh/_exa"

{{ $ageVersion := (gitHubLatestRelease "FiloSottile/age").TagName -}}
["{{- $bdir -}}/age"]
    type = "file"
    url = "https://github.com/FiloSottile/age/releases/download/{{ $ageVersion }}/age-{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    ["{{- $bdir -}}/age".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]

["{{- $bdir -}}/kubectl"]
  type = "file"
  url = "https://dl.k8s.io/release/{{ output "wget" "-q" "-O" "-" "https://dl.k8s.io/release/stable.txt" }}/bin/{{ .chezmoi.os }}/{{ .chezmoi.arch }}/kubectl"
  executable = true

[".zplugins/zshrc.d"]
    type = "archive"
    url = "https://github.com/mattmc3/zshrc.d/archive/refs/heads/main.zip"
    stripComponents = 1
    extract = true
    include = ["*/*.zsh"]
    refreshPeriod = "168h"

["{{- $bdir -}}/direnv"]
  type = "file"
  url = "https://github.com/direnv/direnv/releases/download/{{ (gitHubLatestRelease "direnv/direnv").TagName }}/direnv.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable = true

["{{- $bdir -}}/fzf"]
  type = "file"
  url = "https://github.com/junegunn/fzf/releases/download/{{ (gitHubLatestRelease "junegunn/fzf").TagName }}/fzf-{{ (gitHubLatestRelease "junegunn/fzf").TagName }}-{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
  executable = true
  ["{{- $bdir -}}/fzf" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fzf"]

[".zshrc.d/fzf-keybindings.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/{{ (gitHubLatestRelease "junegunn/fzf").TagName }}/shell/key-bindings.zsh"

["{{- $cdir -}}/_fzf"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/{{ (gitHubLatestRelease "junegunn/fzf").TagName }}/shell/completion.zsh"


["{{- $bdir -}}/bat"]
  type = "file"
  url = "https://github.com/sharkdp/bat/releases/download/{{ (gitHubLatestRelease "sharkdp/bat").TagName }}/bat-{{ (gitHubLatestRelease "sharkdp/bat").TagName }}-x86_64-unknown-linux-gnu.tar.gz"
  executable = true
  ["{{- $bdir -}}/bat" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-{{ (gitHubLatestRelease "sharkdp/bat").TagName }}-x86_64-unknown-linux-gnu/bat"]

["{{- $cdir -}}/_bat"]
  type = "file"
  url = "https://github.com/sharkdp/bat/releases/download/{{ (gitHubLatestRelease "sharkdp/bat").TagName }}/bat-{{ (gitHubLatestRelease "sharkdp/bat").TagName }}-x86_64-unknown-linux-gnu.tar.gz"
  ["{{- $cdir -}}/_bat" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-{{ (gitHubLatestRelease "sharkdp/bat").TagName }}-x86_64-unknown-linux-gnu/autocomplete/bat.zsh"]


["{{- $bdir -}}/rg"]
  type = "file"
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}/ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  ["{{- $bdir -}}/rg" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl/rg"]

["{{- $cdir -}}/_rg"]
  type = "file"
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}/ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl.tar.gz"
  ["{{- $cdir -}}/_rg" .filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "ripgrep-{{ (gitHubLatestRelease "BurntSushi/ripgrep").TagName }}-x86_64-unknown-linux-musl/complete/_rg"]

[".asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
