---
- ansible.builtin.include_role:
    name: _github
  vars:
    name: "Direnv"
    repo: "direnv/direnv"
    current_version_cmd: "/usr/local/bin/direnv --version | awk 'NR==1' | sed 's/^/v/'"
    output: "/usr/local/bin/direnv"
    filename: "direnv.linux-%ARCH%"

- name: "Direnv | Ensure {{ ansible_user_dir }}/.config/direnv dir exists"
  file: 
    path: "{{ ansible_user_dir }}/.config/direnv"
    state: directory

- name: "Direnv | Copy direnv.toml"
  ansible.builtin.copy:
    src: "direnv.toml"
    dest: "{{ ansible_user_dir }}/.config/direnv/direnv.toml"
    mode: "0644"
