---
- name: Direnv | Install from Github
  ansible.builtin.include_role:
    name: github
  vars:
    github_task_name: Direnv
    github_repo: direnv/direnv
    github_current_version_cmd: /usr/local/bin/direnv --version | awk 'NR==1' | sed 's/^/v/'
    github_output: /usr/local/bin/direnv
    github_filename: direnv.linux-%ARCH%

- name: Direnv | Ensure {{ ansible_user_dir }}/.config/direnv dir exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/direnv"
    state: directory

- name: Direnv | Copy direnv.toml
  ansible.builtin.copy:
    src: direnv.toml
    dest: "{{ ansible_user_dir }}/.config/direnv/direnv.toml"
    mode: "0644"
