---
- name: Kubectl | Get latest version
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/stable.txt"
    return_content: true
  register: k8s_version

- name: Kubectl | Get installed version
  ansible.builtin.shell: /usr/local/bin/kubectl version 2>&1 | awk 'NR==1{print $3; exit}'
  register: k8s_installed_version

- name: Kubectl | Show k8s_version debug
  ansible.builtin.debug:
    var: k8s_version.content

- name: Kubectl | Show k8s_installed_version debug
  ansible.builtin.debug:
    var: k8s_installed_version.stdout


- name: Kubectl | Install
  when: k8s_version.content not in k8s_installed_version.stdout
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ k8s_version.content }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"
    force: true
  become: true
