---
- name: Zsh | Copy .zshenv
  ansible.builtin.copy:
    src: .zshenv
    dest: "{{ ansible_user_dir }}/.zshenv"
    mode: "0644"

- name: Zsh | Ensure {{ ansible_user_dir }}/.config/zsh dir exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/zsh"
    state: directory

- name: Zsh | Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_user_dir }}/.config/zsh/.zshrc"
    mode: "0644"

- name: Zsh | Copy .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: "{{ ansible_user_dir }}/.config/zsh/.zprofile"
    mode: "0644"

- name: Zsh | Copy custom zsh config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/snippets"
    src: snippets/
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: Zsh | Copy WSL zsh config
  when: ansible_host_environment_is_wsl
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/zsh/snippets"
    src: wsl.zsh
    mode: "0644"
    force: true

- name: Zsh | Set default terminal
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  ignore_errors: true
  become: true

- name: Zsh | Detect zinit
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/zinit"
  register: zinit

- name: Zsh | Register zinit state
  ansible.builtin.set_fact:
    zinit_is_installed: "{{ zinit.stat.exists }}"

- name: Zsh | Debug zinit_is_installed
  ansible.builtin.debug:
    var: zinit_is_installed

- name: Zsh | Install zinit
  when: not zinit_is_installed
  ansible.builtin.git:
    repo: https://github.com/zdharma-continuum/zinit.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.config/zinit"
