---
- name: Go-Lang | Install dependencies
  ansible.builtin.dnf:
    pkg:
      - curl
      - gcc
      - git
      - findutils
      - make
      - rsync
      - tar
      - jq
    state: present
  register: dnf_result
  become: true
  until: dnf_result is success
  retries: 1
  delay: 2
