---
- name: LSD | Install from Github
  ansible.builtin.include_role:
    name: github
  vars:
    github_task_name: LSD
    github_repo: lsd-rs/lsd
    github_current_version_cmd: /usr/local/bin/lsd --version | sed 's/lsd /v/'
    github_output: /usr/local/bin/lsd
    github_filename: lsd-%VERSION%-%ARCHRAW%-unknown-linux-gnu.tar.gz
    github_extracted_name: lsd-%VERSION%-%ARCHRAW%-unknown-linux-gnu/lsd

- name: LSD | Ensure {{ ansible_user_dir }}/.config/lsd dir exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/lsd"
    state: directory

- name: LSD | Copy custom config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/lsd/config.yaml"
    src: config.yaml
    mode: "0644"
