---
- name: Cleanup {{ github_task_name }} compressed file
  ansible.builtin.file:
    path: /tmp/{{ github_pkg_filename }}
    state: absent
  become: true

- name: Remove extracted {{ github_task_name }} directory
  when: (github_pkg_filename.find('.tar') != -1) or (github_pkg_filename.find('.zip') != -1)
  ansible.builtin.file:
    path: /tmp/{{ github_extracted_name | split('/') | first }}
    state: absent
  become: true
