- name: "1Password | Add RPM Key"
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    fingerprint: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

- name: "1Password | Add RPM Repo"
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch/
    gpgcheck: yes
    gpgkey:
      - https://downloads.1password.com/linux/keys/1password.asc
  become: true

- name: "1Password | Install 1Password CLI"
  ansible.builtin.dnf:
    name: 1password-cli
    state: present
  become: true

- name: "1Password | Install 1Password"
  ansible.builtin.dnf:
    name: 1password
    state: present
  become: true
