---
- name: "Neovim | {{ ansible_distribution }} | Configure repository"
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: true

- name: Neovim | {{ ansible_distribution }} | Install nvim
  ansible.builtin.apt:
    name:
      - neovim
      - python3-neovim
    state: latest
  become: true
